# constants.ps1 — Code generated by cmd/genhooks; DO NOT EDIT.
# Source: internal/paths/paths.go, internal/session/state.go
$script:DataDirRel    = '.agentcord'
$script:StateFile     = 'state.json'
$script:PidFile       = 'daemon.pid'
$script:SessionsDir   = 'sessions'
$script:SessionExt    = '.session'
$script:BinaryName    = 'agentcord'
$script:StateVersion  = 1
