// Package main implements the genhooks tool that generates constants.sh and
// constants.ps1 from the Go source of truth in internal/paths and
// internal/session.
//
// It is invoked by go generate via the directive in internal/paths/paths.go.
package main

import (
	"fmt"
	"os"
	"strings"

	"tools.zach/dev/agentcord/internal/paths"
	"tools.zach/dev/agentcord/internal/session"
)

// genHeader returns the standard two-line header for a generated constants file.
func genHeader(filename string) string {
	return fmt.Sprintf(
		"# %s — Code generated by cmd/genhooks; DO NOT EDIT.\n# Source: internal/paths/paths.go, internal/session/state.go\n",
		filename,
	)
}

func main() {
	if err := writeBash(); err != nil {
		fmt.Fprintf(os.Stderr, "write constants.sh: %v\n", err)
		os.Exit(1)
	}
	if err := writePowerShell(); err != nil {
		fmt.Fprintf(os.Stderr, "write constants.ps1: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote constants.sh and constants.ps1")
}

func writeBash() error {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString(genHeader("constants.sh"))
	fmt.Fprintf(&b, "DATA_DIR_REL=%q\n", paths.DataDirRel)
	fmt.Fprintf(&b, "STATE_FILE=%q\n", paths.StateFile)
	fmt.Fprintf(&b, "PID_FILE=%q\n", paths.PIDFile)
	fmt.Fprintf(&b, "SESSIONS_DIR=%q\n", paths.SessionsDir)
	fmt.Fprintf(&b, "SESSION_EXT=%q\n", paths.SessionExt)
	fmt.Fprintf(&b, "BINARY_NAME=%q\n", paths.BinaryName)
	fmt.Fprintf(&b, "STATE_VERSION=%d\n", session.CurrentVersion)

	// go generate runs from internal/paths/; ../../ reaches repo root.
	return os.WriteFile("../../scripts/hooks/lib/unix/constants.sh", []byte(b.String()), 0o644)
}

func writePowerShell() error {
	var b strings.Builder
	b.WriteString(genHeader("constants.ps1"))
	fmt.Fprintf(&b, "$script:DataDirRel    = '%s'\n", paths.DataDirRel)
	fmt.Fprintf(&b, "$script:StateFile     = '%s'\n", paths.StateFile)
	fmt.Fprintf(&b, "$script:PidFile       = '%s'\n", paths.PIDFile)
	fmt.Fprintf(&b, "$script:SessionsDir   = '%s'\n", paths.SessionsDir)
	fmt.Fprintf(&b, "$script:SessionExt    = '%s'\n", paths.SessionExt)
	fmt.Fprintf(&b, "$script:BinaryName    = '%s'\n", paths.BinaryName)
	fmt.Fprintf(&b, "$script:StateVersion  = %d\n", session.CurrentVersion)

	return os.WriteFile("../../scripts/hooks/lib/windows/constants.ps1", []byte(b.String()), 0o644)
}
