name: Feature Request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Display/formatting
        - Privacy
        - Config
        - Pricing
        - Idle behavior
        - Buttons
        - Multi-client
        - Statusline
        - Installer
        - New tool integration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? (optional)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches? (optional)
    validations:
      required: false
