#!/usr/bin/env bash
# constants.sh — Code generated by cmd/genhooks; DO NOT EDIT.
# Source: internal/paths/paths.go, internal/session/state.go
DATA_DIR_REL=".agentcord"
STATE_FILE="state.json"
PID_FILE="daemon.pid"
SESSIONS_DIR="sessions"
SESSION_EXT=".session"
BINARY_NAME="agentcord"
STATE_VERSION=1
